version: "3.8"

services:
  jupyter:
    build:
      context: .
    ports:
      - 8888:8888
    working_dir: /work
    volumes:
      - ./src:/work:cached
    container_name: jupyter-notebook-container

  jupyter-pytorch:
    build:
      context: .
      dockerfile: Dockerfile.pytorch
    ports:
      - 8888:8888
    working_dir: /work
    volumes:
      - ./src:/work:cached
    container_name: jupyter-notebook-container-pytorch
    ## Uncomment the below lines if your device don't have suported GPUs 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  jupyter-pytorch-bert:
    build:
      context: .
      dockerfile: Dockerfile.pytorch-bert
    ports:
      - 8888:8888
    working_dir: /work
    volumes:
      - ./src:/work:cached
    container_name: jupyter-notebook-container-pytorch-bert
    ## Uncomment the below lines if your device don't have suported GPUs 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
